### ISSUE TITLE
Real examples of file names for modules

### ISSUE THREAD

**Issue by ctran** [griddynamics/mpl#73]
I would like to see real examples of the stage names and the module hierarchy if you're willing to share.

Thanks.

**Comment by sparshev** [comment]
Hi @ctran,

So I can't share the customer's pipeline structure, but you can check the half-completed real-example `example-cicd` nested library - the names in it is based on the real project automation and the `vars/ExampleProjectPipeline.groovy` definition are quite the same as the one was used.

Unfortunately I'm stuck with the docker certificates for this example, but hopefully will find some time to find a way and complete it.

Overall I'm trying to keep it simple for every project - and since they are usually microservices - the logic is not very complex. The only thing is with build version generated automatically and the deployment procedures should use the right helm packages.

Thank you

**Comment by ctran** [comment]
I've looked at those.  They are pretty small set, I'm hoping to see a bigger list to compare with what I need to do.  

I appreciate you taking time answering my query, however.

**Comment by sparshev** [comment]
Sorry, @ctran - the MPL is not an automation solution database. It's a framework to simplify build your own solutions and what we have right now - that's the only thing I can share as open source.

If you need some extra expertise for your company projects - I can only suggest to contact [Grid Dynamics](https://www.griddynamics.com/contact) for any professional support.
